import type { FindResult } from "./find";
import { opportunityScore, tierOf } from "./score";

/**
 * Client-side .xlsx export of a listicle report. Dynamically imports exceljs so
 * it stays out of the main bundle. Only the selected rows are exported when
 * `onlyUrls` is provided; otherwise the full report.
 */
export async function downloadListiclesXlsx(
  result: FindResult,
  onlyUrls?: Set<string>,
) {
  const ExcelJS = (await import("exceljs")).default;
  const wb = new ExcelJS.Workbook();
  wb.creator = "Linkurst";
  wb.created = new Date();

  const ws = wb.addWorksheet("Listicles");
  const drLabel = result.daSource === "ahrefs" ? "DR (Ahrefs)" : "Authority";
  ws.columns = [
    { header: "Opportunity", key: "opp", width: 12 },
    { header: "Tier", key: "tier", width: 10 },
    { header: "Listicle", key: "title", width: 50 },
    { header: "URL", key: "url", width: 52 },
    { header: "Domain", key: "domain", width: 24 },
    { header: drLabel, key: "da", width: 12 },
    { header: "PA", key: "pa", width: 8 },
    { header: "Est. traffic/mo", key: "traffic", width: 16 },
    { header: "Google rank", key: "pos", width: 12 },
    { header: "Updated", key: "updated", width: 14 },
    { header: "You featured?", key: "mentions", width: 14 },
    { header: "Competitors featured", key: "comps", width: 34 },
  ];

  const header = ws.getRow(1);
  header.font = { bold: true, color: { argb: "FF1C1C1E" } };
  header.eachCell((c) => {
    c.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFFBE4DE" } };
    c.alignment = { vertical: "middle" };
  });

  const rows = result.listicles
    .filter((l) => !onlyUrls || onlyUrls.has(l.url))
    .sort((a, b) => opportunityScore(b) - opportunityScore(a));
  for (const l of rows) {
    const score = opportunityScore(l);
    ws.addRow({
      opp: score,
      tier: tierOf(score),
      title: l.title,
      url: l.url,
      domain: l.domain,
      da: l.da ?? "",
      pa: l.pa ?? "",
      traffic: l.traffic ?? "",
      pos: l.bestPosition,
      updated: l.updated ?? "",
      mentions: l.mentionsBrand == null ? "" : l.mentionsBrand ? "Yes" : "No",
      comps: l.competitorsMentioned.join(", "),
    });
  }
  ws.autoFilter = { from: "A1", to: "L1" };
  ws.views = [{ state: "frozen", ySplit: 1 }];

  // Meta sheet with the query + attribution.
  const meta = wb.addWorksheet("About");
  meta.columns = [{ width: 20 }, { width: 60 }];
  meta.addRows([
    ["Keyword", result.keyword],
    ["Location", result.location],
    ["Your website", result.brandDomain ?? ""],
    ["Competitors", result.competitors.join(", ")],
    ["Listicles found", result.totals.listicles],
    ["Placement gaps", result.totals.gaps],
    ["Generated by", "Linkurst · linkurst.com"],
    ["Domain Rating", "Domain Rating by Ahrefs (ahrefs.com)"],
  ]);
  meta.getColumn(1).font = { bold: true };

  const buf = await wb.xlsx.writeBuffer();
  const blob = new Blob([buf], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `linkurst-listicles-${result.keyword
    .replace(/[^a-z0-9]+/gi, "-")
    .slice(0, 40)
    .replace(/^-|-$/g, "")}.xlsx`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
