import type { FindResult } from "./find";
import { opportunityScore } from "./score";

/**
 * Client-side .xlsx export of a listicle report. Dynamically imports exceljs so
 * it stays out of the main bundle. Only the selected rows are exported when
 * `onlyUrls` is provided; otherwise the full report.
 *
 * Styled as a clean, presentable table: a numbered index column, a branded
 * bold header, centered numeric columns with thousands separators, hairline
 * borders, a frozen + filtered header row, and the Inter font throughout.
 */
export async function downloadListiclesXlsx(
  result: FindResult,
  onlyUrls?: Set<string>,
) {
  const ExcelJS = (await import("exceljs")).default;
  const wb = new ExcelJS.Workbook();
  wb.creator = "Linkurst";
  wb.created = new Date();

  const FONT = "Inter";
  const CHARCOAL = "FF1C1C1E";
  const CORAL = "FFE8553A";
  const HEADER_BG = "FFFBEDE8"; // coral-wash
  const BORDER = "FFE7E1D8";
  const hair = { style: "thin" as const, color: { argb: BORDER } };

  const ws = wb.addWorksheet("Listicles", {
    views: [{ state: "frozen", ySplit: 1 }],
  });
  const drLabel = result.daSource === "ahrefs" ? "DR (Ahrefs)" : "Authority";

  // Column definitions: key, header, width, and horizontal alignment.
  const cols: { key: string; header: string; width: number; align: "left" | "center" }[] = [
    { key: "idx", header: "#", width: 5, align: "center" },
    { key: "title", header: "Listicle", width: 46, align: "left" },
    { key: "url", header: "URL", width: 52, align: "left" },
    { key: "domain", header: "Domain", width: 22, align: "left" },
    { key: "da", header: drLabel, width: 12, align: "center" },
    { key: "pa", header: "PA", width: 8, align: "center" },
    { key: "traffic", header: "Est. traffic/mo", width: 16, align: "center" },
    { key: "pos", header: "Google rank", width: 13, align: "center" },
    { key: "updated", header: "Updated", width: 14, align: "center" },
    { key: "author", header: "Author", width: 20, align: "left" },
    { key: "mentions", header: "You featured?", width: 14, align: "center" },
    { key: "comps", header: "Competitors featured", width: 34, align: "left" },
  ];
  ws.columns = cols.map((c) => ({ key: c.key, width: c.width }));

  // Header row.
  const header = ws.getRow(1);
  header.height = 26;
  cols.forEach((c, i) => {
    const cell = header.getCell(i + 1);
    cell.value = c.header;
    cell.font = { name: FONT, bold: true, size: 11, color: { argb: CHARCOAL } };
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: HEADER_BG } };
    cell.alignment = { vertical: "middle", horizontal: c.align, wrapText: false };
    cell.border = {
      top: hair,
      left: hair,
      right: hair,
      bottom: { style: "medium", color: { argb: CORAL } },
    };
  });

  const rows = result.listicles
    .filter((l) => !onlyUrls || onlyUrls.has(l.url))
    .sort((a, b) => opportunityScore(b) - opportunityScore(a));

  rows.forEach((l, i) => {
    const row = ws.addRow({
      idx: i + 1,
      title: l.title,
      url: l.url,
      domain: l.domain,
      da: l.da ?? "",
      pa: l.pa ?? "",
      traffic: l.traffic ?? "",
      pos: l.bestPosition > 0 ? l.bestPosition : "",
      updated: l.updated ?? "",
      author: l.author ?? "",
      mentions: l.mentionsBrand == null ? "—" : l.mentionsBrand ? "Yes" : "No",
      comps: l.competitorsMentioned.join(", "),
    });
    row.height = 20;
    cols.forEach((c, ci) => {
      const cell = row.getCell(ci + 1);
      cell.font = { name: FONT, size: 10, color: { argb: CHARCOAL } };
      cell.alignment = { vertical: "middle", horizontal: c.align };
      cell.border = { top: hair, left: hair, right: hair, bottom: hair };
      if (c.key === "traffic") cell.numFmt = "#,##0";
      if (c.key === "url") {
        // Make the URL a real clickable link, styled subtly.
        cell.value = { text: l.url, hyperlink: l.url };
        cell.font = { name: FONT, size: 10, color: { argb: "FF8A8A8E" }, underline: true };
      }
      if (c.key === "mentions") {
        cell.font = {
          name: FONT,
          size: 10,
          bold: true,
          color: { argb: l.mentionsBrand === false ? CORAL : CHARCOAL },
        };
      }
    });
  });

  ws.autoFilter = { from: "A1", to: `${String.fromCharCode(64 + cols.length)}1` };

  // Meta sheet with the query + attribution.
  const meta = wb.addWorksheet("About");
  meta.columns = [{ width: 20 }, { width: 60 }];
  const metaRows: [string, string | number][] = [
    ["Keyword", result.keyword],
    ["Location", result.location],
    ["Your website", result.brandDomain ?? ""],
    ["Competitors", result.competitors.join(", ")],
    ["Listicles found", result.totals.listicles],
    ["Generated by", "Linkurst · linkurst.com"],
    ["Domain Rating", "Domain Rating by Ahrefs (ahrefs.com)"],
  ];
  meta.addRows(metaRows);
  meta.eachRow((row) => {
    row.getCell(1).font = { name: FONT, bold: true, color: { argb: CHARCOAL } };
    row.getCell(2).font = { name: FONT, color: { argb: CHARCOAL } };
  });

  const buf = await wb.xlsx.writeBuffer();
  const blob = new Blob([buf], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `linkurst-listicles-${result.keyword
    .replace(/[^a-z0-9]+/gi, "-")
    .slice(0, 40)
    .replace(/^-|-$/g, "")}.xlsx`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
